export type Product = {
  slug: string;
  name: string;
  team: string;
  year: string;
  price: number;
  description: string;
  story: string;
  image: string;
  category: "selecciones" | "clubes" | "chile";
  badge?: "TIER S" | "TIER A" | "TIER B" | "ÚLTIMAS UNIDADES";
};

export const products: Product[] = [
  {
    slug: "brasil-1970",
    name: "Brasil 1970",
    team: "Selección de Brasil",
    year: "1970",
    price: 35990,
    description: "La camiseta amarilla más icónica del fútbol mundial. La de Pelé, Jairzinho y Carlos Alberto en el Mundial de México 70.",
    story: "Brasil ganó su tercer título mundial vistiendo este modelo que cambió la estética del fútbol para siempre. Considerada por la FIFA como la mejor selección de la historia.",
    image: "/products/brasil-1970.svg",
    category: "selecciones",
    badge: "TIER S",
  },
  {
    slug: "argentina-1986",
    name: "Argentina 1986",
    team: "Selección de Argentina",
    year: "1986",
    price: 37990,
    description: "La camiseta de Maradona en México 86. La 'Mano de Dios' y el 'Gol del Siglo' en una sola pieza de historia.",
    story: "Diego Armando Maradona elevó esta camiseta a categoría de mito tras el partido ante Inglaterra. Argentina campeón del mundo.",
    image: "/products/argentina-1986.svg",
    category: "selecciones",
    badge: "TIER S",
  },
  {
    slug: "chile-1998",
    name: "Chile 1998",
    team: "La Roja",
    year: "1998",
    price: 32990,
    description: "La camiseta de la generación dorada. Salas, Zamorano, el regreso a un mundial después de 16 años.",
    story: "Francia 98 marcó a una generación entera de chilenos. La 'Ro-Sa' (Zamorano-Salas) hizo historia con esta tricota.",
    image: "/products/chile-1998.svg",
    category: "chile",
    badge: "TIER S",
  },
  {
    slug: "holanda-1988",
    name: "Holanda 1988",
    team: "Países Bajos",
    year: "1988",
    price: 34990,
    description: "La 'Naranja Mecánica' campeona de Europa. El diseño de Adidas que se volvió leyenda.",
    story: "Van Basten, Gullit y Rijkaard llevaron a Holanda a su única gran corona internacional. Diseño icónico de los 80s.",
    image: "/products/holanda-1988.svg",
    category: "selecciones",
    badge: "TIER S",
  },
  {
    slug: "francia-1998",
    name: "Francia 1998",
    team: "Selección de Francia",
    year: "1998",
    price: 35990,
    description: "Los Bleus campeones del mundo en casa. Zidane, Thuram, la generación que cambió Francia.",
    story: "El primer título mundial francés. Una camiseta que simboliza la unidad de un país a través del fútbol.",
    image: "/products/francia-1998.svg",
    category: "selecciones",
    badge: "TIER A",
  },
  {
    slug: "italia-1990",
    name: "Italia 1990",
    team: "La Azzurra",
    year: "1990",
    price: 33990,
    description: "Italia 90: 'Notti Magiche'. Schillaci, el llanto de Maradona y el azul más bello del fútbol.",
    story: "El mundial en casa para Italia. Aunque cayeron en semifinales, esta camiseta quedó grabada en la historia.",
    image: "/products/italia-1990.svg",
    category: "selecciones",
    badge: "TIER A",
  },
  {
    slug: "alemania-1990",
    name: "Alemania 1990",
    team: "Die Mannschaft",
    year: "1990",
    price: 33990,
    description: "El diseño más icónico de la historia. Las franjas tricolor que definieron una década entera.",
    story: "Alemania campeona del mundo en Italia 90 con Matthäus, Klinsmann y Brehme. El diseño más reconocible de los 90s.",
    image: "/products/alemania-1990.svg",
    category: "selecciones",
    badge: "TIER A",
  },
  {
    slug: "milan-1990",
    name: "AC Milan 1990",
    team: "Associazione Calcio Milan",
    year: "1989-1990",
    price: 36990,
    description: "El Milan de Sacchi. Van Basten, Gullit, Rijkaard. El equipo más dominante de fines de los 80s.",
    story: "Bicampeón consecutivo de la Copa de Europa. Considerados por muchos como el mejor equipo de clubes de la historia.",
    image: "/products/milan-1990.svg",
    category: "clubes",
    badge: "TIER A",
  },
  {
    slug: "colo-colo-1991",
    name: "Colo-Colo 1991",
    team: "Club Social y Deportivo Colo-Colo",
    year: "1991",
    price: 36990,
    description: "El Cacique campeón de la Copa Libertadores. Único equipo chileno en lograrlo.",
    story: "Bajo la dirección de Mirko Jozić, Colo-Colo conquistó América. Una hazaña histórica del fútbol chileno.",
    image: "/products/colo-colo-1991.svg",
    category: "chile",
    badge: "TIER S",
  },
  {
    slug: "u-de-chile-1994",
    name: "U. de Chile 1994",
    team: "Universidad de Chile",
    year: "1994",
    price: 34990,
    description: "El año del bicampeonato azul tras 25 años de sequía. Marcelo Salas, Sandrino Castec, gloria pura.",
    story: "La 'U' rompió la maldición de un cuarto de siglo sin títulos. Esta camiseta es el símbolo del renacer azul.",
    image: "/products/u-de-chile-1994.svg",
    category: "chile",
    badge: "TIER A",
  },
  {
    slug: "nigeria-1994",
    name: "Nigeria 1994",
    team: "Super Eagles",
    year: "1994",
    price: 32990,
    description: "El diseño más bello del fútbol africano. Las Super Águilas que enamoraron al mundo en USA 94.",
    story: "Nigeria sorprendió en su primer mundial. Yekini, Amokachi, Amunike. Una camiseta de coleccionista absoluto.",
    image: "/products/nigeria-1994.svg",
    category: "selecciones",
    badge: "TIER A",
  },
  {
    slug: "boca-juniors-2000",
    name: "Boca Juniors 2000",
    team: "Club Atlético Boca Juniors",
    year: "2000",
    price: 35990,
    description: "El Boca de Bianchi. Riquelme en su esplendor, Palermo, Battaglia. Campeones del mundo.",
    story: "Boca venció al Real Madrid 2-1 en la final intercontinental de Tokio. Consagración del proyecto más ganador.",
    image: "/products/boca-2000.svg",
    category: "clubes",
    badge: "TIER A",
  },
];

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);
export const getByCategory = (cat: Product["category"]) => products.filter((p) => p.category === cat);
